###  This program will solve the Taxi problem using RL Q-learning¶

<img src= "Reinforcement_Learning_Taxi_Env.width-1200.png" width="300" height="300" align="centr">


In [36]:
import gym
import numpy as np

In [37]:
env = gym.make('Taxi-v3')

In [38]:
# print the action space size
action_size = env.action_space.n
print("Action size = {}".format(action_size))

Action size = 6


In [39]:
# print state space size
state_size = env.observation_space.n
print("State size = {} ".format(state_size))

State size = 500 


In [40]:
# initialize a Q - table of size state_size X action_size entry for each of the 6 action and 500 states
q_table = np.zeros((state_size, action_size))
print(q_table)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [47]:
# set standard RL parameters
alpha = 0.7  # Learning Rate - alpha
gamma = 0.6  # Discounting Factor - gamma

# Number of episodes 
num_of_episode = 50000 
max_steps = 99  # Max Steps per episode

#  Exploration/Exploitation  parameters
epsilon = 1.0  # Exploration rate
max_epsilon = 1.0  # Exploration probability at start
min_epsilon = 0.01  # Minimum exploration probability
decay_rate = 0.01  # Exponential decay rate for exploration prob

In [48]:
for episode in range(num_of_episode):
    
    # Reset the environment
    state = env.reset() 
        
    for step in range(max_steps):
        
        # choose an action according to epsilon-greedy policy
        # If rand number < less than epsilon - take a random choice (exploration) 
        if np.random.uniform(0, 1) < epsilon:
            action = env.action_space.sample()
            
        # else take action with maximum expected future reward(exploitation)
        else:
            action = np.argmax(q_table[state, :])
           

        # take a step 
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + alpha * [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        q_table[state, action] = q_table[state, action] + alpha * (reward + gamma 
                                                                   * np.max(q_table[new_state, :]) 
                                                                   - q_table[state, action])
        # set new state as cuurent state
        state = new_state

        # If done then finish episode
        if done:
            break

    # decrease epsilon 
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)

env.reset()
print("End Training")

End Training


In [63]:
# see how agent preforms after training
num_of_episode_after_training = 100 
rewards = []

for episode in range(num_of_episode_after_training):
    
    state = env.reset()
    total_rewards = 0

    for step in range(max_steps):
       
        # Take the action that have the maximum expected future reward given that state
        #action = np.argmax(q_table[state, :])
        action = q_table[state].argmax()

        new_state, reward, done, info = env.step(action)

        total_rewards += reward

        if done:
            rewards.append(total_rewards)
            print("Score = {}".format(total_rewards))
            break
        # set new state as cuurent state
        state = new_state

env.close()

# Calculate average reward
print('Score over time = {}'.format(str(sum(rewards) / num_of_episode_after_training)))

Score = 4
Score = 10
Score = 8
Score = 8
Score = 6
Score = 8
Score = 5
Score = 9
Score = 4
Score = 4
Score = 14
Score = 9
Score = 6
Score = 9
Score = 8
Score = 6
Score = 7
Score = 7
Score = 7
Score = 9
Score = 11
Score = 6
Score = 7
Score = 9
Score = 10
Score = 5
Score = 7
Score = 8
Score = 5
Score = 3
Score = 7
Score = 7
Score = 9
Score = 14
Score = 4
Score = 8
Score = 10
Score = 10
Score = 13
Score = 12
Score = 3
Score = 6
Score = 3
Score = 6
Score = 7
Score = 7
Score = 8
Score = 5
Score = 11
Score = 9
Score = 10
Score = 7
Score = 8
Score = 10
Score = 12
Score = 7
Score = 7
Score = 8
Score = 9
Score = 10
Score = 8
Score = 7
Score = 6
Score = 9
Score = 13
Score = 5
Score = 8
Score = 9
Score = 4
Score = 10
Score = 12
Score = 4
Score = 9
Score = 7
Score = 8
Score = 6
Score = 8
Score = 8
Score = 5
Score = 8
Score = 9
Score = 6
Score = 8
Score = 5
Score = 9
Score = 6
Score = 15
Score = 7
Score = 7
Score = 11
Score = 7
Score = 7
Score = 7
Score = 5
Score = 8
Score = 8
Score = 10
Score = 5
